# Uses action: https://github.com/marketplace/actions/easy-versioning
name: EasyVersioning

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Calculate the version
        id: version
        uses: Langsdorf/easy-versioning@1.0.1
        with:
          input: '1.0.0'

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.version }}
