# Uses action: https://github.com/marketplace/actions/github-tag-bump
# Does not use a prerelease version when on another branch that does not yet have any commits.
name: GitHubTagBump-UsesTag

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Calculate the version
        id: dryRunVersion
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          # Set prerelease to true if not pushing to the default branch.
          PRERELEASE: ${{ github.event_name != 'push' || github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
          # Append truncated commit SHA to prerelease tag.
          # PRERELEASE_SUFFIX: ${{ github.sha }}
          DRY_RUN: true

      - name: Display the version
        run: |
          echo new_tag: ${{ steps.dryRunVersion.outputs.new_tag }}
          echo tag: ${{ steps.dryRunVersion.outputs.tag }}
          echo part: ${{ steps.dryRunVersion.outputs.part }}

      - name: Set the new version tag
        id: version
        # Only run this step if we are doing a push (not a PR) to the default branch (e.g. main).
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
