# Uses action: https://github.com/marketplace/actions/github-tag-bump
# Does not use a prerelease version when on another branch that does not yet have any commits.
# Must provide a PRERELEASE_SUFFIX so that different branches do not end up with the same prerelease version.
# When a prerelease verison is generated, it does not provide just the stable version number part to use in .NET assemblies that do not support prerelease versions.
name: GitHubTagBump-UsesTag

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine the version
        id: version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          # Set prerelease to true if not pushing to the default branch.
          PRERELEASE: ${{ github.event_name != 'push' || github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
          # Use the commit sha as the prerelease suffix so different branches have different prerelease versions.
          PRERELEASE_SUFFIX: ${{ github.sha }}
          DRY_RUN: true

      - name: Display the version
        run: |
          echo new_tag: ${{ steps.version.outputs.new_tag }}
          echo tag: ${{ steps.version.outputs.tag }}
          echo part: ${{ steps.version.outputs.part }}

      # - name: Set the new version tag
      #   # Only run this step if we are doing a push (not a PR) to the default branch (e.g. main).
      #   if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      #   uses: anothrNick/github-tag-action@1.67.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CUSTOM_TAG: ${{ steps.version.outputs.new_tag }}
