# Uses action: https://github.com/marketplace/actions/git-version
# Requires also installing the libevent package to detect the previous version tag :(
# Generates a nicely formatted prerelease version number: {MAJOR}.{MINOR}.{PATCH}-{sanitized-branch-name}.{commits-distance}.{hash}
name: GitVersion-UsesTag

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Calculate the version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          # The name of the release branch
          release-branch: main # default is master
          # The name of the dev branch
          dev-branch: # default is dev
          # The prefix to use in the version
          prefix: # optional
          # The paths to be used to calculate changes (comma-separated)
          log-paths: # optional, default is ./

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.version }}
          echo Previous version: ${{ steps.version.outputs.previous-version }}
