name: GitVersion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set the version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          # The name of the release branch
          release-branch: main # default is master
          # The name of the dev branch
          dev-branch: # default is dev
          # The prefix to use in the version
          prefix: # optional
          # The paths to be used to calculate changes (comma-separated)
          log-paths: # optional, default is ./

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.version }}

      - name: Display the previous version
        run: |
          echo Previous version: ${{ steps.version.outputs.previous-version }}
