# Uses action: https://github.com/marketplace/actions/git-version
# Requires also installing the libevent package to properly detect the previous version tag :(
# Generates a nicely formatted prerelease version number: {MAJOR}.{MINOR}.{PATCH}-{sanitized-branch-name}.{commits-distance}.{hash}
name: GitVersion-UsesTag

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the whole repo history.

      - name: Calculate the version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main # default is master
          prefix: v # default is empty

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.version }}
          echo Previous version: ${{ steps.version.outputs.previous-version }}
