# Uses action: https://github.com/marketplace/actions/git-version
# Must include 'fetch-depth: 0' in checkout step to get all tags for it to determine the previous version.
# Generates a nicely formatted prerelease version number: {MAJOR}.{MINOR}.{PATCH}-{sanitized-branch-name}.{commits-distance}.{hash}
# When a prerelease verison is generated, it does not provide just the stable version number part to use in .NET assemblies that do not support prerelease versions.
name: GitVersion-UsesTag

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the whole repo history.

      - name: Determine the version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main # default is master
          prefix: v # default is empty

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.version }}
          echo Previous version: ${{ steps.version.outputs.previous-version }}

      # - name: Set the new version tag
      #   # Only run this step if we are doing a push (not a PR) to the default branch (e.g. main).
      #   if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      #   run: |
      #     git tag ${{ steps.version.outputs.version }}
      #     git push origin ${{ steps.version.outputs.version }}
