# Uses action: https://github.com/marketplace/actions/increment-version
name: IncrementVersion

on:
  push:
    branches: main
  pull_request:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Calculate the version
        id: version
        uses: christian-draeger/increment-semantic-version@1.0.3
        with:
          current-version: '1.0.0'
          version-fragment: 'bug'

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.next-version }}
