# Uses action: https://github.com/marketplace/actions/version-bump
# Does not support creating prerelease versions :(
name: VersionBump-UsesTag

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Calculate the version
        id: version
        uses: opspresso/action-version@v0.2.8

      - name: Display the version
        run: |
          echo Version: ${{ steps.version.outputs.version }}
